name: on_upgrade
description: Local upgrade checker plugin. Provides the ability to compare the currently running app version against a saved one. Enables the developer to easily migrate data between upgrades or to show users a new features dialog.
version: 0.0.2
homepage: https://github.com/Boehrsi/on_upgrade

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^0.6.4
  pub_semver: ^1.4.4
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:

