name: on_upgrade
description: Local upgrade checker plugin. Provides the ability to compare the currently running app version against a saved one.
version: 1.2.0
homepage: https://github.com/Boehrsi/on_upgrade
repository: https://github.com/Boehrsi/on_upgrade/
issue_tracker: https://github.com/Boehrsi/on_upgrade/issues
topics: [ update, upgrade, utils ]

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ">=2.0.0 <10.0.0"
  pub_semver: ^2.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.2 <7.0.0"

platforms:
  android:
  ios:
  web: