name: Analyze
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}