name: Main
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  analyze:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1