name: Test and upload coverage
on:
  push:
    branches: [main, develop]
jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1